services:
  kafka:
    image: bitnami/kafka:3.7.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes


  uploader:
    build: ./uploader
    env_file: .env
    volumes:
      - ./uploader/data:/data
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  processor:
    build: ./processor
    env_file: .env
    volumes:
      - ./processor/data:/data
    depends_on:
      - kafka

  notifier:
    build: ./notifier
    env_file: .env
    volumes:
      - ./notifier/data:/data
    depends_on:
      - kafka
